### ISSUE TITLE
Android initialazing failed

### ISSUE THREAD

**Issue by mtarin** [DigitalStrawberry/ANE-Bugsnag#1]
There any trick to use the ANE in android?

Following the example dont fires the library, with the following error:

[Fault] exception, information=ReferenceError: Error #1065: Variable com.bugsnag::Bugsnag is not defined.
java.lang.ArrayIndexOutOfBoundsException: -2
    at flash.tools.debugger.concrete.ScriptText.getLine(ScriptText.java:38)
    at flash.tools.debugger.concrete.DModule.getLine(DModule.java:135)
    at flex.tools.debugger.cli.DebugCLI.dumpBreakLine(DebugCLI.java:2485)
    at flex.tools.debugger.cli.DebugCLI.dumpHaltState(DebugCLI.java:2289)
    at flex.tools.debugger.cli.DebugCLI.runningLoop(DebugCLI.java:2821)
    at flex.tools.debugger.cli.DebugCLI.process(DebugCLI.java:817)
    at flex.tools.debugger.cli.DebugCLI.execute(DebugCLI.java:669)
    at flex.tools.debugger.cli.DebugCLI.main(DebugCLI.java:461)

The code:

private function initialize(event:Event):void
{
        Bugsnag.init(GeneralData.bugsnag_ios_key, GeneralData.bugsnag_android_key);
}

The iOS seems to initialize ok, its expressed in the bugsnag dashboard.

**Comment by ecornbower** [comment]
It looks like you are not packaging the ANE within the Android version. Check your app manifest and make sure that the ANE is properly packaged within your application.

**Comment by mtarin** [comment]
Now i'm getting the error descripted in this link:

https://forums.adobe.com/thread/1426125

It seems that a default files used in the ANE compilation clashes in the app compilation (strings.xml, etc.)

The error:

aapt tool failed:C:\Users\User\AppData\Local\Temp\bbb58a42-c111-49a8-8478-3c77f206a2fb\app_entry_res\values\strings.xml:19: error: Resource at app_version appears in overlay but not in the base package; use <add-resource> to add.

.. continue with more errors of the same class

**Comment by ecornbower** [comment]
Are you compiling on Windows or on a Mac? We haven't tested compiling on a Windows machine, so that may be the problem.

Have you tried building the test file included in the source? Do you get the same error?

**Comment by mtarin** [comment]
Hi Kevin, im using Windows 8 with Intellij Idea 14.1

I've didn't try because i dont know how to, but i'll try and let you know.

**Comment by ecornbower** [comment]
There is an IntelliJ project set up in the root directory of the repo. You should be able to open that up and compile the test project directly to your Android device.

**Comment by vforsh** [comment]
Hey guys,

Unfortunately, I've encountered similar issue when building for Android (Win 10, Intellij IDEA, latest AIR SDK v22). When I'm adding Bugsnag ane to <extensions> list, I get the next error:

```
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    at com.android.dx.command.dexer.Main.processClass(Main.java:709)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
    at com.android.dx.command.dexer.Main.access$300(Main.java:83)
    at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at ...
```

And thanks a lot for FREE extension! It works great with iOS.

**Comment by ecornbower** [comment]
Thanks for reporting this, I'll take a look into it and get back to you.

**Comment by vforsh** [comment]
ANE can't be compiled for Android because it was compiled with JDK 8.

Could you please re-compile it using JDK 7? http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

I've recompiled android part and it works. But since I don't have a Mac I can't compile iOS part.

You need to modify Android part of **build.xml**

```
<javac srcdir="../android/src" destdir="../android/temp/classes" includeantruntime="false" target="1.7" source="1.7">
```

Thanks in advance!

**Comment by ecornbower** [comment]
Thanks for tracking this down, try this version of the ANE and let me know if it works correctly for you.

[ANEBugsnag.ane.zip](https://github.com/DigitalStrawberry/ANE-Bugsnag/files/329112/ANEBugsnag.ane.zip)

**Comment by vforsh** [comment]
It works, both iOS and Android. 

Thanks for a quick fix!

**Comment by ecornbower** [comment]
Glad to hear that it is fixed. In the future you should download the latest release version from the "releases" section. Those are are always tested to work on iOS and Android, where the latest commit may not be.
